### PR TITLE
Smoother difficulty retargetting

### PR DESCRIPTION
**Pull request by btcdrak**
Increases the sampling time and adjusting the bounds to achieve smoother retargetting.

This must also be backported to `0.10.x`

Refs #6

### CODE REVIEW

**Comment by btcdrak** [comment]
Looking for ACKs @reorder @petertodd @GrynnSan and anyone else who cares to look.

**Comment by petertodd** [comment]
This is where I'm going to pull out my "I've got a fine arts degree" card and claim ignorance. :)

Seriously, screwing around with difficulty retargetting is one of those things that gmaxwell has bad things to say about, and I'll trust his judgement on that. OTOH, he's saying that in the context of Bitcoin, which already has a simple diff algorithm. I totally get why alts do it for perception reasons, but I'm completely unwilling to put my stamp of approval on such things.

OTOH, I will say it doesn't look like the code is trying to steal anyone's coins, and the fork switch bit looks ok at first glance. If you haven't already, you should have a set of test blocks made up to try it out on testnet. (disable/override the time if you have too)

**Comment by btcdrak** [comment]
@petertodd The issue is the difficulty retargetting as it stands is too reactive and thus overshoots in both directions. So it's just a matter of trying to get it to behave more smoothly. Even with a stable hash rate, the current code will cause wild diff swings. The plan is to test this on testnet before merging.

**Comment by btcdrak** [comment]
I've pushed a `difftestnet` branch cherry-pick based on `0.10` since `master` branch is not ready for production use. I'll upgrade our testnet next week and we can play a little.

**Comment by petertodd** [comment]
@btcdrak To be clear, I'm not disagreeing with you! I'm just saying in the case of a secure coin with stable hashing power, the Satoshi algorithm is fine and preferable for a lot of reasons. It's only coins where the security situation isn't so clear because of intra-coin hashing competition that all this stuff matters, which is why I want nothing to do with the discussion.

**Comment by btcdrak** [comment]
@petertodd Thanks! That's clear.

**Comment by reorder** [comment]
I am going to make a simulation in a day or two, charting difficulty changes in different miners behaviour patterns.

**Comment by reorder** [comment]
I have made a blocksearch simulation with old and new parameters: https://gist.github.com/reorder/be3d680edd467d8cffc4

It still has some flaws (simulates only constant hashrate and random past/future timestamps instead of real timewarp attack), but it already shows tuned parameters work better:

```
500000 blocks, no timewarp, window 24, clamp 3
Max blocktime: 279 sec
Number of 2x blocktime misses: 17021 (3.40 %)
Number of 3x blocktime misses: 5058 (1.01 %)
Number of 5x blocktime misses: 721 (0.14 %)
Number of 10x blocktime misses: 5 (0.00 %)

500000 blocks, no timewarp, window 72, clamp 2
Max blocktime: 176 sec
Number of 2x blocktime misses: 11553 (2.31 %)
Number of 3x blocktime misses: 1889 (0.38 %)
Number of 5x blocktime misses: 67 (0.01 %)
Number of 10x blocktime misses: 0 (0.00 %)

500000 blocks, timewarp, window 24, clamp 3
Max blocktime: 366 sec
Number of 2x blocktime misses: 12563 (2.51 %)
Number of 3x blocktime misses: 4375 (0.88 %)
Number of 5x blocktime misses: 731 (0.15 %)
Number of 10x blocktime misses: 19 (0.00 %)

500000 blocks, timewarp, window 72, clamp 2
Max blocktime: 285 sec
Number of 2x blocktime misses: 17295 (3.46 %)
Number of 3x blocktime misses: 5705 (1.14 %)
Number of 5x blocktime misses: 833 (0.17 %)
Number of 10x blocktime misses: 10 (0.00 %)
```

**Comment by reorder** [comment]
Simulation on 'real' hashrate, pulled from blockchain, averaged over 5 blocks. Each scenario is ran 3 times. In this scenario, tuning makes almost no difference:

```
200000 blocks, no timewarp, window 24, clamp 3 pass 0
Max blocktime: 1366 sec
Number of 2x blocktime misses: 9582 (4.79 %)
Number of 3x blocktime misses: 4407 (2.20 %)
Number of 5x blocktime misses: 1381 (0.69 %)
Number of 10x blocktime misses: 195 (0.10 %)

200000 blocks, no timewarp, window 24, clamp 3 pass 1
Max blocktime: 1158 sec
Number of 2x blocktime misses: 9565 (4.78 %)
Number of 3x blocktime misses: 4457 (2.23 %)
Number of 5x blocktime misses: 1417 (0.71 %)
Number of 10x blocktime misses: 203 (0.10 %)

200000 blocks, no timewarp, window 24, clamp 3 pass 2
Max blocktime: 1076 sec
Number of 2x blocktime misses: 9520 (4.76 %)
Number of 3x blocktime misses: 4400 (2.20 %)
Number of 5x blocktime misses: 1383 (0.69 %)
Number of 10x blocktime misses: 164 (0.08 %)

200000 blocks, no timewarp, window 72, clamp 2 pass 0
Max blocktime: 824 sec
Number of 2x blocktime misses: 8659 (4.33 %)
Number of 3x blocktime misses: 3903 (1.95 %)
Number of 5x blocktime misses: 1157 (0.58 %)
Number of 10x blocktime misses: 151 (0.08 %)

200000 blocks, no timewarp, window 72, clamp 2 pass 1
Max blocktime: 977 sec
Number of 2x blocktime misses: 8593 (4.30 %)
Number of 3x blocktime misses: 3813 (1.91 %)
Number of 5x blocktime misses: 1234 (0.62 %)
Number of 10x blocktime misses: 179 (0.09 %)

200000 blocks, no timewarp, window 72, clamp 2 pass 2
Max blocktime: 937 sec
Number of 2x blocktime misses: 8725 (4.36 %)
Number of 3x blocktime misses: 3868 (1.93 %)
Number of 5x blocktime misses: 1178 (0.59 %)
Number of 10x blocktime misses: 153 (0.08 %)

200000 blocks, timewarp, window 24, clamp 3 pass 0
Max blocktime: 1242 sec
Number of 2x blocktime misses: 5832 (2.92 %)
Number of 3x blocktime misses: 3007 (1.50 %)
Number of 5x blocktime misses: 1146 (0.57 %)
Number of 10x blocktime misses: 239 (0.12 %)

200000 blocks, timewarp, window 24, clamp 3 pass 1
Max blocktime: 1229 sec
Number of 2x blocktime misses: 6232 (3.12 %)
Number of 3x blocktime misses: 3246 (1.62 %)
Number of 5x blocktime misses: 1256 (0.63 %)
Number of 10x blocktime misses: 281 (0.14 %)

200000 blocks, timewarp, window 24, clamp 3 pass 2
Max blocktime: 2848 sec
Number of 2x blocktime misses: 6038 (3.02 %)
Number of 3x blocktime misses: 3147 (1.57 %)
Number of 5x blocktime misses: 1253 (0.63 %)
Number of 10x blocktime misses: 253 (0.13 %)

200000 blocks, timewarp, window 72, clamp 2 pass 0
Max blocktime: 1392 sec
Number of 2x blocktime misses: 9010 (4.50 %)
Number of 3x blocktime misses: 4484 (2.24 %)
Number of 5x blocktime misses: 1646 (0.82 %)
Number of 10x blocktime misses: 298 (0.15 %)

200000 blocks, timewarp, window 72, clamp 2 pass 1
Max blocktime: 1483 sec
Number of 2x blocktime misses: 8974 (4.49 %)
Number of 3x blocktime misses: 4460 (2.23 %)
Number of 5x blocktime misses: 1564 (0.78 %)
Number of 10x blocktime misses: 285 (0.14 %)

200000 blocks, timewarp, window 72, clamp 2 pass 2
Max blocktime: 1729 sec
Number of 2x blocktime misses: 9028 (4.51 %)
Number of 3x blocktime misses: 4583 (2.29 %)
Number of 5x blocktime misses: 1654 (0.83 %)
Number of 10x blocktime misses: 289 (0.14 %)
```

**Comment by reorder** [comment]
ACK

**Pull request merged**
